---
# tasks file for wilsonma.ad-ds-init
- name: Install Active Directory Feature
  win_feature:
    name: AD-Domain-Services
    state: present

- win_domain:
    dns_domain_name: ansible.test
    safe_mode_password: password123!
  register: update_result

- win_reboot:
  when: update.result.reboot_required

