---
# tasks file for wilsonma.ad-ds-init
- name: Install Active Directory Feature
  win_feature:
    name: AD-Domain-Services
    state: present

- win_domain:
    dns_domain_name: ansible.test
    safe_mode_password: password123!

- name: Create Windows Domain Controller
  win_domain_controller:
    dns_domain_name: ansible.test
    domain_admin_user: admin@ansible.test
    domain_admin_password: password123!
    safe_mode_password: password123!
    state: domain_controller
    log_path: c:\ansible_win_domain_controller.txt

